import Foundation
import SwiftUI
import Combine

enum SupportedLanguage: String, CaseIterable {
    case english = "en"
    case spanish = "es"
    case french = "fr"
    case hebrew = "he"
    case mandarin = "zh-Hans"
    case cantonese = "zh-Hant"
    case portuguese = "pt"
    case arabic = "ar"
    case russian = "ru"
    case german = "de"
    
    var name: String {
        switch self {
        case .english: return "English"
        case .spanish: return "Español"
        case .portuguese: return "Português"
        case .hebrew: return "עברית"
        case .mandarin: return "中文"
        case .cantonese: return "粵語"
        case .french: return "Français"
        case .german: return "Deutsch"
        case .arabic: return "العربية"
        case .russian: return "Русский"

        }
    }
    
    var isRTL: Bool {
        return self == .arabic || self == .hebrew
    }
    
    var flag: String {
        switch self {
        case .english: return "🇺🇸"
        case .spanish: return "🇪🇸"
        case .portuguese: return "🇵🇹"
        case .hebrew: return "🇮🇱"
        case .mandarin: return "🇨🇳"
        case .cantonese: return "🇨🇩"
        case .french: return "🇫🇷"
        case .german: return "🇩🇪"
        case .arabic: return "🇦🇪"
        case .russian: return "🇷🇺"
        }
    }
}

enum FontSizePreference: String, CaseIterable {
    case small = "small"
    case large = "large"
    
    var name: String {
        switch self {
        case .small: return "Small"
        case .large: return "Large"
        }
    }
    
    var icon: String {
        switch self {
        case .small: return "textformat.size.smaller"
        case .large: return "textformat.size.larger"
        }
    }
    
    var multiplier: CGFloat {
        switch self {
        case .small: return 0.9
        case .large: return 1.1
        }
    }
}

class LanguageManager: ObservableObject {
    static let shared = LanguageManager()
    
    @Published var currentLanguage: SupportedLanguage = .english
    @Published var currentFontSize: FontSizePreference = .small
    
    private let userDefaults = UserDefaults.standard
    private let languageKey = "selectedLanguage"
    private let fontSizeKey = "selectedFontSize"
    
    private init() {
        loadSettings()
    }
    
    func setLanguage(_ language: SupportedLanguage) {
        currentLanguage = language
        userDefaults.set(language.rawValue, forKey: languageKey)
    }
    
    func setFontSize(_ fontSize: FontSizePreference) {
        currentFontSize = fontSize
        userDefaults.set(fontSize.rawValue, forKey: fontSizeKey)
    }
    
    private func loadSettings() {
        if let savedLanguage = userDefaults.string(forKey: languageKey),
           let language = SupportedLanguage(rawValue: savedLanguage) {
            currentLanguage = language
        }
        
        if let savedFontSize = userDefaults.string(forKey: fontSizeKey),
           let fontSize = FontSizePreference(rawValue: savedFontSize) {
            currentFontSize = fontSize
        }
    }
    
    func translate(_ key: String) -> String {
        return translations[currentLanguage]?[key] ?? key
    }
    
    func scaledFontSize(_ baseSize: CGFloat) -> CGFloat {
        return baseSize * currentFontSize.multiplier
    }
    
    var isRTL: Bool {
        return currentLanguage.isRTL
    }
}

// Add font size translations to the dictionary
let translations: [SupportedLanguage: [String: String]] = [
    .english: [
        // Auth
        "welcome_back": "Welcome Back",
        "sign_in": "Sign In",
        "sign_up": "Sign Up",
        "welcome_to_devspace": "Welcome to DevSpace 👋",
        "sign_in_description": "Sign in to access your workspace.",
        "sign_up_description": "Create your account to get started.",
        "full_name": "Full name",
        "username": "Username",
        "company_email": "Company email",
        "email": "Email",
        "password": "Password",
        "create_account": "Create Account",
        "forgot_password": "Forgot Password?",
        "continue_with_apple": "Continue with Apple",
        "continue_with_google": "Continue with Google",
        "continue_with_github": "Continue with GitHub",
        "privacy_policy_terms": "Privacy Policy and Terms and Conditions",
        "or": "or",
        
        // Sign Out
        "sign_out": "Sign Out",
        "sign_out_failed": "Sign out failed: {error}",
        
        // Time Formatting
        "time_now": "now",
        "time_min_short": "min",
        "time_hr_short": "hr",
        "time_hrs_short": "hrs",
        "time_day_short": "day",
        "time_days_short": "days",
        "time_wk_short": "wk",
        "time_wks_short": "wks",
        "time_mo_short": "mo",
        "time_mos_short": "mos",
        "time_yr_short": "yr",
        "time_yrs_short": "yrs",
        "time_minute": "minute",
        "time_minutes": "minutes",
        "time_hour": "hour",
        "time_hours": "hours",
        "time_day": "day",
        "time_days": "days",
        "time_week": "week",
        "time_weeks": "weeks",
        "time_month": "month",
        "time_months": "months",
        "time_year": "year",
        "time_years": "years",
        "time_ago": "ago",
        "time_over": "over",
        "logo_image": "Scratch 3",
        // Sidebar & UI
        "search_placeholder": "Search...",
        "new_note_tooltip": "Create New Note",
        "reset_filters_tooltip": "Reset filters and search",
        "reset_filters": "Reset Filters",
        "sort": "Sort",
        "date_created": "Date Created",
        "last_modified": "Last Modified",
        "category": "Category",
        "all_notes": "All Notes",
        "all_categories": "All Categories",
        "uncategorized": "Uncategorized",
        "tags": "Tags",
        "all_tags": "All Tags",
        "no_notes": "No Notes",
        "no_results": "No Results",
        "create_first_note": "Create a new note to get started.",
        "search_no_results": "No notes match your search.",
        "move_to_trash": "Move to Trash",
        "delete_permanently": "Delete Permanently",
        "restore_to_saved": "Restore to Saved",
        "pin_note": "Pin Note",
        "unpin_note": "Unpin Note",
        "unviewed_reminder": "Unviewed reminder",
        "untitled": "Untitled",
        "just_now": "just now",
        "settings": "Settings",
        "appearance_language": "Appearance & Language",
        "font_size": "Font Size",
        "show_filter_labels": "Show Labels",
        "page_title": "Page Title",
        "note_metadata": "Note Metadata",
        "json_output": "JSON Output",
        "format": "Format",
        "text_formatting_tooltip": "Text Formatting (Aa)",
        "untitled_note": "Untitled Note",
        "delete_table": "Delete Table",
        "delete_accordion": "Delete Accordion",
        "delete_code_block": "Delete Code Block",
        "delete_quote": "Delete Quote",
        "delete_bookmark": "Delete Bookmark",
        "delete_file_link": "Delete File Link",
        "delete_reminder": "Delete Reminder",
        "type_content_here": "Type Content here",
        "temp": "Temp",
        "deleted": "Deleted",
        "all": "All",
        "saved": "Saved",
        "deleting_soon": "Deleting soon",
        "default_save_location": "Default Save Location",
        "temp_note_duration": "Temp Note Duration",
        "hour": "hour",
        "hours": "hours",
        "days": "days",
        "notes_configuration": "Notes Configuration",
        "cleanup_rules": "Cleanup Rules",
        "done": "Done",
        "no_note_selected": "No Note Selected",
        "select_note_description": "Select a note from the sidebar or create a new one.",
        "clear_search": "Clear search",
        "filter_by_category": "Filter by Category",
        "filter_by_tag": "Filter by Tag",
        "sort_notes": "Sort Notes",
        "extra_large": "Extra Large",
        "large": "Large",
        "medium": "Medium",
        "body_font": "Body",
        "footnote_font": "Footnote",
        "text_color": "Text Color",
        "remove_formatting": "Remove Formatting",
        "convert_to_link": "Convert to Link",
        "note_properties": "Note Properties",
        "status": "Status",
        "categories": "Categories",
        "tags_tab": "Tags",
        "search_create_category": "Search or Create Category...",
        "search_create_tag": "Search or Create Tag...",
        "create_item": "Create \"{name}\"",
        "existing_categories": "Existing Categories",
        "existing_tags": "Existing Tags",
        "current_status": "Current Status",
        "status_description": "Choose a status based on how long you intend to keep this note. This helps keep your notes organized and your workspace clean.",
        "pinned": "Pinned",
        "deleted_notes_info": "Deleted notes are permanently removed after 30 days."
    ],
    .spanish: [
        "time_now": "ahora",
        "time_min_short": "min",
        "time_minute": "minuto",
        "time_minutes": "minutos",
        "logo_image": "Scratch 3",
        "search_placeholder": "Buscar...",
        "new_note_tooltip": "Crear nota nueva",
        "reset_filters_tooltip": "Restablecer filtros y búsqueda",
        "reset_filters": "Restablecer filtros",
        "sort": "Ordenar",
        "date_created": "Fecha de creación",
        "last_modified": "Última modificación",
        "category": "Categoría",
        "all_notes": "Todas las notas",
        "all_categories": "Todas las categorías",
        "uncategorized": "Sin categoría",
        "tags": "Etiquetas",
        "all_tags": "Todas las etiquetas",
        "no_notes": "Sin notas",
        "no_results": "Sin resultados",
        "create_first_note": "Crea una nueva nota para empezar.",
        "search_no_results": "Ninguna nota coincide con tu búsqueda.",
        "move_to_trash": "Mover a la papelera",
        "delete_permanently": "Eliminar permanentemente",
        "restore_to_saved": "Restaurar a guardado",
        "pin_note": "Anclar nota",
        "unpin_note": "Desanclar nota",
        "unviewed_reminder": "Recordatorio no visto",
        "untitled": "Sin título",
        "just_now": "ahora mismo",
        "settings": "Ajustes",
        "appearance_language": "Apariencia e idioma",
        "language": "Idioma",
        "font_size": "Tamaño de fuente",
        "show_filter_labels": "Mostrar etiquetas",
        "deleting_soon": "Eliminando pronto",
        "page_title": "Título de la página",
        "note_metadata": "Metadatos de la nota",
        "json_output": "Salida JSON",
        "format": "Formatear",
        "text_formatting_tooltip": "Formato de texto (Aa)",
        "untitled_note": "Nota sin título",
        "delete_table": "Eliminar tabla",
        "delete_accordion": "Eliminar acordeón",
        "delete_code_block": "Eliminar bloque de código",
        "delete_quote": "Eliminar cita",
        "delete_bookmark": "Eliminar marcador",
        "delete_file_link": "Eliminar enlace de archivo",
        "delete_reminder": "Eliminar recordatorio",
        "type_content_here": "Escribe el contenido aquí",
        "temp": "Temp",
        "deleted": "Eliminado",
        "all": "Todo",
        "saved": "Guardado",
        "default_save_location": "Ubicación de guardado predeterminada",
        "temp_note_duration": "Duración de nota temporal",
        "hour": "hora",
        "hours": "horas",
        "days": "días",
        "notes_configuration": "Configuración de notas",
        "cleanup_rules": "Reglas de limpieza",
        "done": "Hecho",
        "no_note_selected": "Ninguna nota seleccionada",
        "select_note_description": "Selecciona una nota de la barra lateral o crea una nueva.",
        "clear_search": "Borrar búsqueda",
        "filter_by_category": "Filtrar por categoría",
        "filter_by_tag": "Filtrar por etiqueta",
        "sort_notes": "Ordenar notas",
        "extra_large": "Extra grande",
        "large": "Grande",
        "medium": "Mediano",
        "body_font": "Cuerpo",
        "footnote_font": "Nota al pie",
        "text_color": "Color de texto",
        "remove_formatting": "Eliminar formato",
        "convert_to_link": "Convertir en enlace",
        "note_properties": "Propiedades de la nota",
        "status": "Estado",
        "categories": "Categorías",
        "tags_tab": "Etiquetas",
        "search_create_category": "Buscar o crear categoría...",
        "search_create_tag": "Buscar o crear etiqueta...",
        "create_item": "Crear \"{name}\"",
        "existing_categories": "Categorías existentes",
        "existing_tags": "Etiquetas existentes",
        "current_status": "Estado actual",
        "status_description": "Elige un estado basado en cuánto tiempo planeas conservar esta nota. Esto ayuda a mantener tus notas organizadas y tu espacio de trabajo limpio.",
        "pinned": "Anclada",
        "deleted_notes_info": "Las notas eliminadas se borran permanentemente después de 30 días."
    ],
    .french: [
        "welcome_back": "Bon retour",
        "sign_in": "Se connecter",
        "sign_up": "S'inscrire",
        "welcome_to_devspace": "Bienvenue sur DevSpace 👋",
        "sign_in_description": "Connectez-vous pour accéder à votre espace de travail.",
        "sign_up_description": "Créez votre compte pour commencer.",
        "full_name": "Nom complet",
        "username": "Nom d'utilisateur",
        "company_email": "E-mail professionnel",
        "email": "E-mail",
        "password": "Mot de passe",
        "create_account": "Créer un compte",
        "forgot_password": "Mot de passe oublié ?",
        "continue_with_apple": "Continuer avec Apple",
        "continue_with_google": "Continuer avec Google",
        "continue_with_github": "Continuer avec GitHub",
        "privacy_policy_terms": "Politique de confidentialité et conditions générales",
        "or": "ou",
        "sign_out": "Se déconnecter",
        "sign_out_failed": "La déconnexion a échoué : {error}",
        "time_now": "maintenant",
        "time_min_short": "min",
        "time_minute": "minute",
        "time_minutes": "minutes",
        "logo_image": "Scratch 3",
        "search_placeholder": "Rechercher...",
        "new_note_tooltip": "Créer une nouvelle note",
        "reset_filters_tooltip": "Réinitialiser les filtres et la recherche",
        "reset_filters": "Réinitialiser les filtres",
        "sort": "Trier",
        "date_created": "Date de création",
        "last_modified": "Dernière modification",
        "category": "Catégorie",
        "all_notes": "Toutes les notes",
        "all_categories": "Toutes les catégories",
        "uncategorized": "Sans catégorie",
        "tags": "Étiquettes",
        "all_tags": "Toutes les étiquettes",
        "no_notes": "Aucune note",
        "no_results": "Aucun résultat",
        "create_first_note": "Créez une nouvelle note pour commencer.",
        "search_no_results": "Aucune note ne correspond à votre recherche.",
        "move_to_trash": "Mettre à la corbeille",
        "delete_permanently": "Supprimer définitivement",
        "restore_to_saved": "Restaurer dans les notes enregistrées",
        "pin_note": "Épingler la note",
        "unpin_note": "Désépingler la note",
        "unviewed_reminder": "Rappel non consulté",
        "untitled": "Sans titre",
        "just_now": "à l'instant",
        "settings": "Paramètres",
        "appearance_language": "Apparence et langue",
        "language": "Langue",
        "font_size": "Taille de police",
        "show_filter_labels": "Afficher les étiquettes",
        "deleting_soon": "Suppression imminente",
        "page_title": "Titre de la page",
        "note_metadata": "Métadonnées de la note",
        "json_output": "Sortie JSON",
        "format": "Format",
        "text_formatting_tooltip": "Formatage du texte (Aa)",
        "untitled_note": "Note sans titre",
        "delete_table": "Supprimer le tableau",
        "delete_accordion": "Supprimer l'accordéon",
        "delete_code_block": "Supprimer le bloc de code",
        "delete_quote": "Supprimer la citation",
        "delete_bookmark": "Supprimer le signet",
        "delete_file_link": "Supprimer le lien de fichier",
        "delete_reminder": "Supprimer le rappel",
        "type_content_here": "Tapez le contenu ici",
        "temp": "Temp",
        "deleted": "Supprimé",
        "all": "Tout",
        "saved": "Enregistré",
        "default_save_location": "Emplacement d'enregistrement par défaut",
        "temp_note_duration": "Durée de la note temporaire",
        "hour": "heure",
        "hours": "heures",
        "days": "jours",
        "notes_configuration": "Configuration des notes",
        "cleanup_rules": "Règles de nettoyage",
        "done": "Terminé",
        "no_note_selected": "Aucune note sélectionnée",
        "select_note_description": "Sélectionnez une note dans la barre latérale ou créez-en une nouvelle.",
        "clear_search": "Effacer la recherche",
        "filter_by_category": "Filtrer par catégorie",
        "filter_by_tag": "Filtrer par étiquette",
        "sort_notes": "Trier les notes",
        "extra_large": "Très grand",
        "large": "Grand",
        "medium": "Moyen",
        "body_font": "Corps",
        "footnote_font": "Note de bas de page",
        "text_color": "Couleur du texte",
        "remove_formatting": "Supprimer le formatage",
        "convert_to_link": "Convertir en lien",
        "note_properties": "Propriétés de la note",
        "status": "Statut",
        "categories": "Catégories",
        "tags_tab": "Étiquettes",
        "search_create_category": "Rechercher ou créer une catégorie...",
        "search_create_tag": "Rechercher ou créer une étiquette...",
        "create_item": "Créer \"{name}\"",
        "existing_categories": "Catégories existantes",
        "existing_tags": "Étiquettes existantes",
        "current_status": "Statut actuel",
        "status_description": "Choisissez un statut en fonction de la durée pendant laquelle vous avez l'intention de conserver cette note. Cela aide à garder vos notes organisées et votre espace de travail propre.",
        "pinned": "Épinglé",
        "deleted_notes_info": "Les notes supprimées sont définitivement retirées après 30 jours."
    ],
    .german: [
        "welcome_back": "Willkommen zurück",
        "sign_in": "Anmelden",
        "sign_up": "Registrieren",
        "welcome_to_devspace": "Willkommen bei DevSpace 👋",
        "sign_in_description": "Melden Sie sich an, um auf Ihren Arbeitsbereich zuzugreifen.",
        "sign_up_description": "Erstellen Sie Ihr Konto, um loszulegen.",
        "full_name": "Vollständiger Name",
        "username": "Benutzername",
        "company_email": "Geschäftliche E-Mail",
        "email": "E-Mail",
        "password": "Passwort",
        "create_account": "Konto erstellen",
        "forgot_password": "Passwort vergessen?",
        "continue_with_apple": "Mit Apple fortfahren",
        "continue_with_google": "Mit Google fortfahren",
        "continue_with_github": "Mit GitHub fortfahren",
        "privacy_policy_terms": "Datenschutzerklärung und Geschäftsbedingungen",
        "or": "oder",
        "sign_out": "Abmelden",
        "sign_out_failed": "Abmeldung fehlgeschlagen: {error}",
        "time_now": "jetzt",
        "time_min_short": "Min.",
        "time_minute": "Minute",
        "time_minutes": "Minuten",
        "logo_image": "Scratch 3",
        "search_placeholder": "Suchen...",
        "new_note_tooltip": "Neue Notiz erstellen",
        "reset_filters_tooltip": "Filter und Suche zurücksetzen",
        "reset_filters": "Filter zurücksetzen",
        "sort": "Sortieren",
        "date_created": "Erstellungsdatum",
        "last_modified": "Zuletzt geändert",
        "category": "Kategorie",
        "all_notes": "Alle Notizen",
        "all_categories": "Alle Kategorien",
        "uncategorized": "Nicht kategorisiert",
        "tags": "Tags",
        "all_tags": "Alle Tags",
        "no_notes": "Keine Notizen",
        "no_results": "Keine Ergebnisse",
        "create_first_note": "Erstellen Sie eine neue Notiz, um loszulegen.",
        "search_no_results": "Keine Notizen entsprechen Ihrer Suche.",
        "move_to_trash": "In den Papierkorb verschieben",
        "delete_permanently": "Endgültig löschen",
        "restore_to_saved": "Wiederherstellen",
        "pin_note": "Notiz anheften",
        "unpin_note": "Notiz lösen",
        "unviewed_reminder": "Ungelesene Erinnerung",
        "untitled": "Unbenannt",
        "just_now": "gerade eben",
        "settings": "Einstellungen",
        "appearance_language": "Aussehen & Sprache",
        "language": "Sprache",
        "font_size": "Schriftgröße",
        "show_filter_labels": "Labels anzeigen",
        "deleting_soon": "Löschung in Kürze",
        "page_title": "Seitentitel",
        "note_metadata": "Notiz-Metadaten",
        "json_output": "JSON-Ausgabe",
        "format": "Format",
        "text_formatting_tooltip": "Textformatierung (Aa)",
        "untitled_note": "Unbenannte Notiz",
        "delete_table": "Tabelle löschen",
        "delete_accordion": "Akkordeon löschen",
        "delete_code_block": "Codeblock löschen",
        "delete_quote": "Zitat löschen",
        "delete_bookmark": "Lesezeichen löschen",
        "delete_file_link": "Dateilink löschen",
        "delete_reminder": "Erinnerung löschen",
        "type_content_here": "Inhalt hier eingeben",
        "temp": "Temp",
        "deleted": "Gelöscht",
        "all": "Alle",
        "saved": "Gespeichert",
        "default_save_location": "Standard-Speicherort",
        "temp_note_duration": "Dauer temporärer Notizen",
        "hour": "Stunde",
        "hours": "Stunden",
        "days": "Tage",
        "notes_configuration": "Notiz-Konfiguration",
        "cleanup_rules": "Bereinigungsregeln",
        "done": "Fertig",
        "no_note_selected": "Keine Notiz ausgewählt",
        "select_note_description": "Wählen Sie eine Notiz aus der Seitenleiste aus oder erstellen Sie eine neue.",
        "clear_search": "Suche löschen",
        "filter_by_category": "Nach Kategorie filtern",
        "filter_by_tag": "Nach Tag filtern",
        "sort_notes": "Notizen sortieren",
        "extra_large": "Sehr groß",
        "large": "Groß",
        "medium": "Mittel",
        "body_font": "Textkörper",
        "footnote_font": "Fußnote",
        "text_color": "Textfarbe",
        "remove_formatting": "Formatierung entfernen",
        "convert_to_link": "In Link umwandeln",
        "note_properties": "Notizeigenschaften",
        "status": "Status",
        "categories": "Kategorien",
        "tags_tab": "Tags",
        "search_create_category": "Kategorie suchen oder erstellen...",
        "search_create_tag": "Tag suchen oder erstellen...",
        "create_item": "\"{name}\" erstellen",
        "existing_categories": "Vorhandene Kategorien",
        "existing_tags": "Vorhandene Tags",
        "current_status": "Aktueller Status",
        "status_description": "Wählen Sie einen Status basierend darauf, wie lange Sie diese Notiz behalten möchten. Dies hilft, Ihren Arbeitsbereich sauber zu halten.",
        "pinned": "Angeheftet",
        "deleted_notes_info": "Gelöschte Notizen werden nach 30 Tagen endgültig entfernt."
    ],
    .portuguese: [
        "welcome_back": "Bem-vindo de volta",
        "sign_in": "Entrar",
        "sign_up": "Cadastrar",
        "welcome_to_devspace": "Bem-vindo ao DevSpace 👋",
        "sign_in_description": "Entre para acessar seu espaço de trabalho.",
        "sign_up_description": "Crie sua conta para começar.",
        "full_name": "Nome completo",
        "username": "Nome de usuário",
        "company_email": "E-mail corporativo",
        "email": "E-mail",
        "password": "Senha",
        "create_account": "Criar conta",
        "forgot_password": "Esqueceu a senha?",
        "continue_with_apple": "Continuar com Apple",
        "continue_with_google": "Continuar com Google",
        "continue_with_github": "Continuar com GitHub",
        "privacy_policy_terms": "Política de Privacidade e Termos e Condições",
        "or": "ou",
        "sign_out": "Sair",
        "sign_out_failed": "Falha ao sair: {error}",
        "time_now": "agora",
        "time_min_short": "min",
        "time_minute": "minuto",
        "time_minutes": "minutos",
        "logo_image": "Scratch 3",
        "search_placeholder": "Buscar...",
        "new_note_tooltip": "Criar Nova Nota",
        "reset_filters_tooltip": "Redefinir filtros e busca",
        "reset_filters": "Redefinir filtros",
        "sort": "Ordenar",
        "date_created": "Data de Criação",
        "last_modified": "Última Modificação",
        "category": "Categoria",
        "all_notes": "Todas as Notas",
        "all_categories": "Todas as categorias",
        "uncategorized": "Sem Categoria",
        "tags": "Tags",
        "all_tags": "Todas as Tags",
        "no_notes": "Sem Notas",
        "no_results": "Sem Resultados",
        "create_first_note": "Crie uma nova nota para começar.",
        "search_no_results": "Nenhuma nota coincide com sua busca.",
        "move_to_trash": "Mover para a Lixeira",
        "delete_permanently": "Excluir Permanentemente",
        "restore_to_saved": "Restaurar para Salvas",
        "pin_note": "Fixar Nota",
        "unpin_note": "Desafixar Nota",
        "unviewed_reminder": "Lembrete não lido",
        "untitled": "Sem título",
        "just_now": "agora mesmo",
        "settings": "Ajustes",
        "appearance_language": "Aparência e Idioma",
        "language": "Idioma",
        "font_size": "Tamanho da Fonte",
        "show_filter_labels": "Mostrar etiquetas",
        "deleting_soon": "Excluindo em breve",
        "page_title": "Título da Página",
        "note_metadata": "Metadados da Nota",
        "json_output": "Saída JSON",
        "format": "Formato",
        "text_formatting_tooltip": "Formatação de Texto (Aa)",
        "untitled_note": "Nota sem título",
        "delete_table": "Excluir Tabela",
        "delete_accordion": "Excluir Acordeão",
        "delete_code_block": "Excluir Bloco de Código",
        "delete_quote": "Excluir Citação",
        "delete_bookmark": "Excluir Marcador",
        "delete_file_link": "Excluir Link de Arquivo",
        "delete_reminder": "Excluir Lembrete",
        "type_content_here": "Digite o conteúdo aqui",
        "temp": "Temp",
        "deleted": "Excluído",
        "all": "Tudo",
        "saved": "Salvo",
        "default_save_location": "Local de Salvamento Padrão",
        "temp_note_duration": "Duração da Nota Temp",
        "hour": "hora",
        "hours": "horas",
        "days": "dias",
        "notes_configuration": "Configuração de Notas",
        "cleanup_rules": "Regras de Limpeza",
        "done": "Concluído",
        "no_note_selected": "Nenhuma Nota Selecionada",
        "select_note_description": "Selecione uma nota na barra lateral ou crie uma nova.",
        "clear_search": "Limpar busca",
        "filter_by_category": "Filtrar por Categoria",
        "filter_by_tag": "Filtrar por Tag",
        "sort_notes": "Ordenar Notas",
        "extra_large": "Muito Grande",
        "large": "Grande",
        "medium": "Médio",
        "body_font": "Corpo",
        "footnote_font": "Nota de Rodapé",
        "text_color": "Cor do Texto",
        "remove_formatting": "Remover Formatação",
        "convert_to_link": "Converter em Link",
        "note_properties": "Propriedades da Nota",
        "status": "Status",
        "categories": "Categorias",
        "tags_tab": "Tags",
        "search_create_category": "Buscar ou Criar Categoria...",
        "search_create_tag": "Buscar ou Criar Tag...",
        "create_item": "Criar \"{name}\"",
        "existing_categories": "Categorias Existentes",
        "existing_tags": "Tags Existentes",
        "current_status": "Status Atual",
        "status_description": "Escolha um status baseado em quanto tempo pretende manter esta nota. Isso ajuda a manter suas notas organizadas e seu espaço limpo.",
        "pinned": "Fixado",
        "deleted_notes_info": "Notas excluídas são removidas permanentemente após 30 dias."
    ],
    .hebrew: [
        "welcome_back": "ברוך הבא",
        "sign_in": "התחברות",
        "sign_up": "הרשמה",
        "welcome_to_devspace": "ברוכים הבאים ל-DevSpace 👋",
        "sign_in_description": "התחבר כדי לגשת לסביבת העבודה שלך.",
        "sign_up_description": "צור חשבון כדי להתחיל.",
        "full_name": "שם מלא",
        "username": "שם משתמש",
        "company_email": "דוא\"ל עסקי",
        "email": "דוא\"ל",
        "password": "סיסמה",
        "create_account": "צור חשבון",
        "forgot_password": "שכחת סיסמה?",
        "continue_with_apple": "המשך עם Apple",
        "continue_with_google": "המשך עם Google",
        "continue_with_github": "המשך עם GitHub",
        "privacy_policy_terms": "מדיניות פרטיות ותנאי שימוש",
        "or": "או",
        "sign_out": "התנתק",
        "sign_out_failed": "נכשל בהתנתקות: {error}",
        "time_now": "עכשיו",
        "time_min_short": "דק'",
        "time_hr_short": "שעה",
        "time_hrs_short": "שעות",
        "time_day_short": "יום",
        "time_days_short": "ימים",
        "time_wk_short": "שבוע",
        "time_wks_short": "שבועות",
        "time_mo_short": "חודש",
        "time_mos_short": "חודשים",
        "time_yr_short": "שנה",
        "time_yrs_short": "שנים",
        "time_minute": "דקה",
        "time_minutes": "דקות",
        "time_hour": "שעה",
        "time_hours": "שעות",
        "time_day": "יום",
        "time_days": "ימים",
        "time_week": "שבוע",
        "time_weeks": "שבועות",
        "time_month": "חודש",
        "time_months": "חודשים",
        "time_year": "שנה",
        "time_years": "שנים",
        "time_ago": "לפני",
        "logo_image": "Scratch 3",
        "search_placeholder": "חיפוש...",
        "new_note_tooltip": "צור פתק חדש",
        "reset_filters_tooltip": "אפס פילטרים וחיפוש",
        "reset_filters": "אפס פילטרים",
        "sort": "מיון",
        "date_created": "תאריך יצירה",
        "last_modified": "שינוי אחרון",
        "category": "קטגוריה",
        "all_notes": "כל הפתקים",
        "all_categories": "כל הקטגוריות",
        "uncategorized": "ללא קטגוריה",
        "tags": "תגיות",
        "all_tags": "כל התגיות",
        "no_notes": "אין פתקים",
        "no_results": "אין תוצאות",
        "create_first_note": "צור פתק חדש כדי להתחיל.",
        "search_no_results": "אין פתקים התואמים לחיפוש שלך.",
        "move_to_trash": "העבר לאשפה",
        "delete_permanently": "מחק לצמיתות",
        "restore_to_saved": "שחזר לשמורים",
        "pin_note": "נעץ פתק",
        "unpin_note": "בטל נעיצת פתק",
        "unviewed_reminder": "תזכורת שלא נצפתה",
        "untitled": "ללא כותרת",
        "just_now": "ממש עכשיו",
        "settings": "הגדרות",
        "appearance_language": "מראה ושפה",
        "language": "שפה",
        "font_size": "גודל גופן",
        "show_filter_labels": "הצג תוויות",
        "page_title": "כותרת עמוד",
        "note_metadata": "מטא-דאטה של הפתק",
        "json_output": "פלט JSON",
        "format": "פורמט",
        "text_formatting_tooltip": "עיצוב טקסט (Aa)",
        "untitled_note": "פתק ללא כותרת",
        "delete_table": "מחק טבלה",
        "delete_accordion": "מחק אקורדיון",
        "delete_code_block": "מחק בלוק קוד",
        "delete_quote": "מחק ציטוט",
        "delete_bookmark": "מחק סימניה",
        "delete_file_link": "מחק קישור לקובץ",
        "delete_reminder": "מחק תזכורת",
        "type_content_here": "הקלד תוכן כאן",
        "temp": "זמני",
        "deleted": "נמחק",
        "all": "הכל",
        "saved": "שמור",
        "deleting_soon": "יימחק בקרוב",
        "default_save_location": "מיקום שמירה ברירת מחדל",
        "temp_note_duration": "משך פתק זמני",
        "hour": "שעה",
        "hours": "שעות",
        "days": "ימים",
        "notes_configuration": "תצורת פתקים",
        "cleanup_rules": "כללי ניקוי",
        "done": "בוצע",
        "no_note_selected": "לא נבחר פתק",
        "select_note_description": "בחר פתק מהתפריט הצדדי או צור אחד חדש.",
        "clear_search": "נקה חיפוש",
        "filter_by_category": "סנן לפי קטגוריה",
        "filter_by_tag": "סנן לפי תגית",
        "sort_notes": "מיין פתקים",
        "extra_large": "גדול מאוד",
        "large": "גדול",
        "medium": "בינוני",
        "body_font": "גוף הטקסט",
        "footnote_font": "הערת שוליים",
        "text_color": "צבע טקסט",
        "remove_formatting": "הסר עיצוב",
        "convert_to_link": "הפוך לקישור",
        "note_properties": "מאפייני פתק",
        "status": "סטטוס",
        "categories": "קטגוריות",
        "tags_tab": "תגיות",
        "search_create_category": "חפש או צור קטגוריה...",
        "search_create_tag": "חפש או צור תגית...",
        "create_item": "צור \"{name}\"",
        "existing_categories": "קטגוריות קיימות",
        "existing_tags": "תגיות קיימות",
        "current_status": "סטטוס נוכחי",
        "status_description": "בחר סטטוס בהתבסס על כמה זמן בכוונתך לשמור פתק זה. זה עוזר לשמור על סביבת עבודה מאורגנת.",
        "pinned": "נעוץ",
        "deleted_notes_info": "פתקים שנמחקו מוסרים לצמיתות לאחר 30 יום."
    ],
    .mandarin: [
        "welcome_back": "欢迎回来",
        "sign_in": "登录",
        "sign_up": "注册",
        "welcome_to_devspace": "欢迎来到 DevSpace 👋",
        "sign_in_description": "登录以访问您的工作空间。",
        "sign_up_description": "创建您的帐户以开始。",
        "full_name": "全名",
        "username": "用户名",
        "company_email": "公司电子邮件",
        "email": "电子邮件",
        "password": "密码",
        "create_account": "创建帐户",
        "forgot_password": "忘记密码？",
        "continue_with_apple": "继续使用 Apple",
        "continue_with_google": "继续使用 Google",
        "continue_with_github": "继续使用 GitHub",
        "privacy_policy_terms": "隐私政策和条款与条件",
        "or": "或",
        "sign_out": "登出",
        "sign_out_failed": "登出失败：{error}",
        "time_now": "现在",
        "time_min_short": "分钟",
        "time_minute": "分钟",
        "time_minutes": "分钟",
        "logo_image": "Scratch 3",
        "search_placeholder": "搜索...",
        "new_note_tooltip": "创建新笔记",
        "reset_filters_tooltip": "重置过滤器和搜索",
        "reset_filters": "重置过滤器",
        "sort": "排序",
        "date_created": "创建日期",
        "last_modified": "最后修改",
        "category": "分类",
        "all_notes": "所有笔记",
        "all_categories": "所有分类",
        "uncategorized": "未分类",
        "tags": "标签",
        "all_tags": "所有标签",
        "no_notes": "无笔记",
        "no_results": "无结果",
        "create_first_note": "创建一个新笔记以开始。",
        "search_no_results": "没有符合您搜索条件的笔记。",
        "move_to_trash": "移至废纸篓",
        "delete_permanently": "永久删除",
        "restore_to_saved": "还原到已保存",
        "pin_note": "固定笔记",
        "unpin_note": "取消固定",
        "unviewed_reminder": "未查看的提醒",
        "untitled": "无标题",
        "just_now": "刚刚",
        "settings": "设置",
        "appearance_language": "外观与语言",
        "language": "语言",
        "font_size": "字体大小",
        "show_filter_labels": "显示标签",
        "deleting_soon": "即将删除",
        "page_title": "页面标题",
        "note_metadata": "笔记元数据",
        "json_output": "JSON 输出",
        "format": "格式",
        "text_formatting_tooltip": "文本格式化 (Aa)",
        "untitled_note": "无标题笔记",
        "delete_table": "删除表格",
        "delete_accordion": "删除折叠面板",
        "delete_code_block": "删除代码块",
        "delete_quote": "删除引用",
        "delete_bookmark": "删除书签",
        "delete_file_link": "删除文件链接",
        "delete_reminder": "删除提醒",
        "type_content_here": "在此输入内容",
        "temp": "临时",
        "deleted": "已删除",
        "all": "全部",
        "saved": "已保存",
        "default_save_location": "默认保存位置",
        "temp_note_duration": "临时笔记时长",
        "hour": "小时",
        "hours": "小时",
        "days": "天",
        "notes_configuration": "笔记配置",
        "cleanup_rules": "清理规则",
        "done": "完成",
        "no_note_selected": "未选择笔记",
        "select_note_description": "从侧边栏选择一个笔记或创建一个新笔记。",
        "clear_search": "清除搜索",
        "filter_by_category": "按分类过滤",
        "filter_by_tag": "按标签过滤",
        "sort_notes": "排序笔记",
        "extra_large": "特大",
        "large": "大",
        "medium": "中",
        "body_font": "正文",
        "footnote_font": "脚注",
        "text_color": "文本颜色",
        "remove_formatting": "清除格式",
        "convert_to_link": "转换为链接",
        "note_properties": "笔记属性",
        "status": "状态",
        "categories": "分类",
        "tags_tab": "标签",
        "search_create_category": "搜索或创建分类...",
        "search_create_tag": "搜索或创建标签...",
        "create_item": "创建 \"{name}\"",
        "existing_categories": "现有分类",
        "existing_tags": "现有标签",
        "current_status": "当前状态",
        "status_description": "根据您打算保留该笔记的时间长度选择一个状态。这有助于保持笔记有条理和工作空间整洁。",
        "pinned": "已固定",
        "deleted_notes_info": "删除的笔记将在 30 天后永久移除。"
    ],
    .cantonese: [
        "welcome_back": "歡迎返嚟",
        "sign_in": "登入",
        "sign_up": "註冊",
        "welcome_to_devspace": "歡迎嚟到 DevSpace 👋",
        "sign_in_description": "登入以訪問你嘅工作空間。",
        "sign_up_description": "建立你嘅帳戶以開始。",
        "full_name": "全名",
        "username": "用戶名",
        "company_email": "公司電子郵件",
        "email": "電子郵件",
        "password": "密碼",
        "create_account": "建立帳戶",
        "forgot_password": "忘記密碼？",
        "continue_with_apple": "繼續使用 Apple",
        "continue_with_google": "繼續使用 Google",
        "continue_with_github": "繼續使用 GitHub",
        "privacy_policy_terms": "隱私政策同條款與條件",
        "or": "或",
        "sign_out": "登出",
        "sign_out_failed": "登出失敗：{error}",
        "time_now": "而家",
        "time_min_short": "分鐘",
        "time_minute": "分鐘",
        "time_minutes": "分鐘",
        "logo_image": "Scratch 3",
        "search_placeholder": "搜尋...",
        "new_note_tooltip": "建立新筆記",
        "reset_filters_tooltip": "重置過濾器同搜尋",
        "reset_filters": "重置過濾器",
        "sort": "排序",
        "date_created": "建立日期",
        "last_modified": "最後修改",
        "category": "分類",
        "all_notes": "所有筆記",
        "all_categories": "所有分類",
        "uncategorized": "未分類",
        "tags": "標籤",
        "all_tags": "所有標籤",
        "no_notes": "無筆記",
        "no_results": "無結果",
        "create_first_note": "建立一個新筆記以開始。",
        "search_no_results": "冇符合你搜尋條件嘅筆記。",
        "move_to_trash": "移至廢紙簍",
        "delete_permanently": "永久刪除",
        "restore_to_saved": "還原到已保存",
        "pin_note": "固定筆記",
        "unpin_note": "取消固定",
        "unviewed_reminder": "未查看嘅提醒",
        "untitled": "無標題",
        "just_now": "剛剛",
        "settings": "設置",
        "appearance_language": "外觀與語言",
        "language": "語言",
        "font_size": "字體大小",
        "show_filter_labels": "顯示標籤",
        "page_title": "頁面標題",
        "note_metadata": "筆記元數據",
        "json_output": "JSON 輸出",
        "format": "格式",
        "text_formatting_tooltip": "文本格式化 (Aa)",
        "untitled_note": "無標題筆記",
        "delete_table": "刪除表格",
        "delete_accordion": "刪除折疊面板",
        "delete_code_block": "刪除代碼塊",
        "delete_quote": "刪除引用",
        "delete_bookmark": "刪除書籤",
        "delete_file_link": "刪除文件鏈接",
        "delete_reminder": "刪除提醒",
        "type_content_here": "喺呢度輸入內容",
        "temp": "臨時",
        "deleted": "已刪除",
        "all": "全部",
        "saved": "已保存",
        "deleting_soon": "即將刪除",
        "default_save_location": "默認保存位置",
        "temp_note_duration": "臨時筆記時長",
        "hour": "小時",
        "hours": "小時",
        "days": "天",
        "notes_configuration": "筆記配置",
        "cleanup_rules": "清理規則",
        "done": "完成",
        "no_note_selected": "未選擇筆記",
        "select_note_description": "從側邊欄選擇一個筆記或建立一個新筆記。",
        "clear_search": "清除搜尋",
        "filter_by_category": "按分類過濾",
        "filter_by_tag": "按標籤過濾",
        "sort_notes": "排序筆記",
        "extra_large": "特大",
        "large": "大",
        "medium": "中",
        "body_font": "正文",
        "footnote_font": "腳註",
        "text_color": "文本顏色",
        "remove_formatting": "清除格式",
        "convert_to_link": "轉換為鏈接",
        "note_properties": "筆記屬性",
        "status": "狀態",
        "categories": "分類",
        "tags_tab": "標籤",
        "search_create_category": "搜尋或建立分類...",
        "search_create_tag": "搜尋或建立標籤...",
        "create_item": "建立 \"{name}\"",
        "existing_categories": "現有分類",
        "existing_tags": "現有標籤",
        "current_status": "當前狀態",
        "status_description": "根據你打算保留核筆記嘅時間長度選擇一個狀態。呢個有助於保持筆記有條理同工作空間整潔。",
        "pinned": "已固定",
        "deleted_notes_info": "刪除嘅筆記將喺 30 天後永久移除。"
    ],
    .arabic: [
        "welcome_back": "مرحباً بعودتك",
        "sign_in": "تسجيل الدخول",
        "sign_up": "إنشاء حساب",
        "welcome_to_devspace": "مرحباً بك في DevSpace 👋",
        "sign_in_description": "سجل دخولك للوصول إلى مساحة عملك.",
        "sign_up_description": "أنشئ حسابك للبدء.",
        "full_name": "الاسم الكامل",
        "username": "اسم المستخدم",
        "company_email": "البريد الإلكتروني للشركة",
        "email": "البريد الإلكتروني",
        "password": "كلمة المرور",
        "create_account": "إنشاء حساب",
        "forgot_password": "هل نسيت كلمة المرور؟",
        "continue_with_apple": "المتابعة باستخدام Apple",
        "continue_with_google": "المتابعة باستخدام Google",
        "continue_with_github": "المتابعة باستخدام GitHub",
        "privacy_policy_terms": "سياسة الخصوصية والشروط والأحكام",
        "or": "أو",
        "sign_out": "تسجيل الخروج",
        "sign_out_failed": "فشل تسجيل الخروج: {error}",
        "time_now": "الآن",
        "time_min_short": "د",
        "time_minute": "دقيقة",
        "time_minutes": "دقائق",
        "logo_image": "Scratch 3",
        "search_placeholder": "بحث...",
        "new_note_tooltip": "إنشاء ملاحظة جديدة",
        "reset_filters_tooltip": "إعادة ضبط الفلاتر والبحث",
        "reset_filters": "إعادة ضبط الفلاتر",
        "sort": "ترتيب",
        "date_created": "تاريخ الإنشاء",
        "last_modified": "آخر تعديل",
        "category": "الفئة",
        "all_notes": "كل الملاحظات",
        "all_categories": "كل الفئات",
        "uncategorized": "غير مصنف",
        "tags": "الوسوم",
        "all_tags": "كل الوسوم",
        "no_notes": "لا يوجد ملاحظات",
        "no_results": "لا يوجد نتائج",
        "create_first_note": "أنشئ ملاحظة جديدة للبدء.",
        "search_no_results": "لا توجد ملاحظات تطابق بحثك.",
        "move_to_trash": "نقل إلى المهملات",
        "delete_permanently": "حذف نهائياً",
        "restore_to_saved": "استعادة إلى المحفوظات",
        "pin_note": "تثبيت الملاحظة",
        "unpin_note": "إلغاء التثبيت",
        "unviewed_reminder": "تذكير غير مقروء",
        "untitled": "بدون عنوان",
        "just_now": "الآن فقط",
        "settings": "الإعدادات",
        "appearance_language": "المظهر واللغة",
        "language": "اللغة",
        "font_size": "حجم الخط",
        "show_filter_labels": "إظهار الملصقات",
        "deleting_soon": "سيتم الحذف قريباً",
        "page_title": "عنوان الصفحة",
        "note_metadata": "بيانات الملاحظة",
        "json_output": "مخرجات JSON",
        "format": "تنسيق",
        "text_formatting_tooltip": "تنسيق النص (Aa)",
        "untitled_note": "ملاحظة بدون عنوان",
        "delete_table": "حذف الجدول",
        "delete_accordion": "حذف الأكورديون",
        "delete_code_block": "حذف كتلة برمجية",
        "delete_quote": "حذف الاقتباس",
        "delete_bookmark": "حذف الإشارة المرجعية",
        "delete_file_link": "حذف رابط الملف",
        "delete_reminder": "حذف التذكير",
        "type_content_here": "اكتب المحتوى هنا",
        "temp": "مؤقت",
        "deleted": "محذوف",
        "all": "الكل",
        "saved": "محفوظ",
        "default_save_location": "موقع الحفظ الافتراضي",
        "temp_note_duration": "مدة الملاحظة المؤقتة",
        "hour": "ساعة",
        "hours": "ساعات",
        "days": "أيام",
        "notes_configuration": "تكوين الملاحظات",
        "cleanup_rules": "قواعد التنظيف",
        "done": "تم",
        "no_note_selected": "لم يتم اختيار ملاحظة",
        "select_note_description": "اختر ملاحظة من الشريط الجانبي أو أنشئ ملاحظة جديدة.",
        "clear_search": "مسح البحث",
        "filter_by_category": "تصفية حسب الفئة",
        "filter_by_tag": "تصفية حسب الوسم",
        "sort_notes": "ترتيب الملاحظات",
        "extra_large": "كبير جداً",
        "large": "كبير",
        "medium": "متوسط",
        "body_font": "النص الأساسي",
        "footnote_font": "حاشية سفلية",
        "text_color": "لون النص",
        "remove_formatting": "إزالة التنسيق",
        "convert_to_link": "تحويل إلى رابط",
        "note_properties": "خصائص الملاحظة",
        "status": "الحالة",
        "categories": "الفئات",
        "tags_tab": "الوسوم",
        "search_create_category": "بحث أو إنشاء فئة...",
        "search_create_tag": "بحث أو إنشاء وسم...",
        "create_item": "إنشاء \"{name}\"",
        "existing_categories": "الفئات الحالية",
        "existing_tags": "الوسوم الحالية",
        "current_status": "الحالة الحالية",
        "status_description": "اختر حالة بناءً على المدة التي تنوي فيها الاحتفاظ بهذه الملاحظة. يساعد هذا في الحفاظ على تنظيم ملاحظاتك ونظافة مساحة عملك.",
        "pinned": "مثبت",
        "deleted_notes_info": "يتم حذف الملاحظات المحذوفة نهائياً بعد 30 يوماً."
    ],
    .russian: [
        "welcome_back": "С возвращением",
        "sign_in": "Войти",
        "sign_up": "Зарегистрироваться",
        "welcome_to_devspace": "Добро пожаловать в DevSpace 👋",
        "sign_in_description": "Войдите, чтобы получить доступ к своему рабочему пространству.",
        "sign_up_description": "Создайте учетную запись, чтобы начать.",
        "full_name": "Полное имя",
        "username": "Имя пользователя",
        "company_email": "Рабочая электронная почта",
        "email": "Электронная почта",
        "password": "Пароль",
        "create_account": "Создать учетную запись",
        "forgot_password": "Забыли пароль?",
        "continue_with_apple": "Продолжить через Apple",
        "continue_with_google": "Продолжить через Google",
        "continue_with_github": "Продолжить через GitHub",
        "privacy_policy_terms": "Политика конфиденциальности и Условия использования",
        "or": "или",
        "sign_out": "Выйти",
        "sign_out_failed": "Ошибка выхода: {error}",
        "time_now": "сейчас",
        "time_min_short": "мин",
        "time_minute": "минута",
        "time_minutes": "минуты",
        "logo_image": "Scratch 3",
        "search_placeholder": "Поиск...",
        "new_note_tooltip": "Создать новую заметку",
        "reset_filters_tooltip": "Сбросить фильтры и поиск",
        "reset_filters": "Сбросить фильтры",
        "sort": "Сортировать",
        "date_created": "Дата создания",
        "last_modified": "Дата изменения",
        "category": "Категория",
        "all_notes": "Все заметки",
        "all_categories": "Все категории",
        "uncategorized": "Без категории",
        "tags": "Теги",
        "all_tags": "Все теги",
        "no_notes": "Заметок нет",
        "no_results": "Нет результатов",
        "create_first_note": "Создайте новую заметку, чтобы начать.",
        "search_no_results": "Заметки не найдены.",
        "move_to_trash": "Переместить в корзину",
        "delete_permanently": "Удалить навсегда",
        "restore_to_saved": "Восстановить в сохраненные",
        "pin_note": "Закрепить заметку",
        "unpin_note": "Открепить заметку",
        "unviewed_reminder": "Непросмотренное напоминание",
        "untitled": "Без названия",
        "just_now": "только что",
        "settings": "Настройки",
        "appearance_language": "Внешний вид и язык",
        "language": "Язык",
        "font_size": "Размер шрифта",
        "show_filter_labels": "Показать ярлыки",
        "deleting_soon": "Скоро будет удалено",
        "page_title": "Заголовок страницы",
        "note_metadata": "Метаданные заметки",
        "json_output": "JSON-вывод",
        "format": "Формат",
        "text_formatting_tooltip": "Форматирование текста (Aa)",
        "untitled_note": "Заметка без названия",
        "delete_table": "Удалить таблицу",
        "delete_accordion": "Удалить аккордеон",
        "delete_code_block": "Удалить блок кода",
        "delete_quote": "Удалить цитату",
        "delete_bookmark": "Удалить закладку",
        "delete_file_link": "Удалить ссылку на файл",
        "delete_reminder": "Удалить напоминание",
        "type_content_here": "Введите содержимое здесь",
        "temp": "Врем.",
        "deleted": "Удалено",
        "all": "Все",
        "saved": "Сохранено",
        "default_save_location": "Место сохранения по умолчанию",
        "temp_note_duration": "Длительность врем. заметки",
        "hour": "час",
        "hours": "часа",
        "days": "дней",
        "notes_configuration": "Конфигурация заметок",
        "cleanup_rules": "Правила очистки",
        "done": "Готово",
        "no_note_selected": "Заметка не выбрана",
        "select_note_description": "Выберите заметку в боковой панели или создайте новую.",
        "clear_search": "Очистить поиск",
        "filter_by_category": "Фильтр по категориям",
        "filter_by_tag": "Фильтр по тегам",
        "sort_notes": "Сортировать заметки",
        "extra_large": "Очень большой",
        "large": "Большой",
        "medium": "Средний",
        "body_font": "Основной текст",
        "footnote_font": "Сноска",
        "text_color": "Цвет текста",
        "remove_formatting": "Удалить форматирование",
        "convert_to_link": "Преобразовать в ссылку",
        "note_properties": "Свойства заметки",
        "status": "Статус",
        "categories": "Категории",
        "tags_tab": "Теги",
        "search_create_category": "Найти или создать категорию...",
        "search_create_tag": "Найти или создать тег...",
        "create_item": "Создать \"{name}\"",
        "existing_categories": "Существующие категории",
        "existing_tags": "Существующие теги",
        "current_status": "Текущий статус",
        "status_description": "Выберите статус в зависимости от того, как долго вы планируете хранить эту заметку. Это поможет поддерживать порядок в заметках и чистоту в рабочем пространстве.",
        "pinned": "Закреплено",
        "deleted_notes_info": "Удаленные заметки навсегда удаляются через 30 дней."
    ]
]
